### ISSUE TITLE
Using intrinsic matrix instead of SDR and pixel size

### ISSUE THREAD

**Issue by haarisr** [eigenvivek/DiffDRR#157]
Is there a way to create a detector and generating DRR's using an intrinsic matrix instead of the SDR and pixel size

**Comment by eigenvivek** [comment]
Hi @haarisr - I think the intrinsic matrix can only give you unit-less versions of the focal length (i.e., 2 * SDR).

If your intrinsic matrix is 
```
fx 0  x0
0  fy y0
0  0  1
```

then your focal length is `f = (fx * dx + fy * dy) / 2` where `dx` and `dy` are the pixel size (in mm or some other unit of length) in the `x` and `y` dimensions. Then `SDR = f / 2`.

If you don't know `dx` and `dy`, you could estimate them by optimizing similarity between DRRs and real X-rays for multiple pixel sizes. However, these parameters are almost always in the DICOM headers for real X-rays.

Hope that helps, let me know if you have any other questions!

**Comment by haarisr** [comment]
Thanks for the quick reply, very helpful advice.

In my images, I do not seem to find the pixel size in the dicom header. I have the intensifier diameter and I know the size of the image.

I am assuming I can divide the diameter by image size to get a rough estimate of the pixel size.
How important do you believe is having a really good estimate of pixel size for the registration?

**Comment by eigenvivek** [comment]
I'm not sure what what the intensifier diameter is. How does it relate to the size of the detector plane?

I've never run a simulation to see how important accurate pixel size estimation is, but my guess is that it is very important (especially if you want registration accuracy on the order of 1-10 mm). That's because the registration losses (eg, L2, NCC, etc) assume correspondence between the pixels in the DRR and the real X-ray. You could rerun the registration tutorial with a moving DRR that has a different pixel size to the original image - perhaps I'm wrong and a rough estimate for pixel size will still lead to accurate registration: https://vivekg.dev/DiffDRR/tutorials/optimizers.html

**Comment by eigenvivek** [comment]
Hi @haarisr going to close this issue, feel free to reopen if you have any further questions.

**Comment by eigenvivek** [comment]
In case anyone stumbles on this thread in the future: `DiffDRR` now has functions to automatically parse an intrinsic camera matrix: https://vivekg.dev/DiffDRR/api/utils.html#intrinsic-matrix-parsing

Given an intrinsic matrix and the detector plane pixel spacings (which should be in the DICOM header), these functions will compute the focal length and principal point of the X-ray source.
