### ISSUE TITLE
Pose based artifacting?

### ISSUE THREAD

**Issue by dimitriSchreib** [eigenvivek/DiffDRR#164]
DRRs from certain poses seem to have a far more "blocky" texture. Is there a parameter that can be tuned to avoid this?
![e8215586-cc1b-4b6c-a4bb-5071a4817146](https://github.com/eigenvivek/DiffDRR/assets/102990188/b9f5c90b-a8bb-49d7-a29c-fc00a381f095)
![034ef9be-244f-480f-8ad4-5ac75f7b2beb](https://github.com/eigenvivek/DiffDRR/assets/102990188/987f8e10-c981-455d-80c2-4cb7eb0c5c4a)

**Comment by eigenvivek** [comment]
Hi @dimitriSchreib, This artifact occurs because Siddon's method for ray tracing is one-ray-per-pixel in the DRR. This causes aliasing that is responsible for the jagged pixel artifacts you observe. However, I'm surprised to see these artifacts at 200x200 resolution. I'm used to only seeing it at 50x50 resolution or below.

- One thing that should fix this artifact is sampling a higher resolution DRR. More pixels in the rendered image means that the changes between adjacent pixels will be smoother.
- A post-processing solution would be to apply a Gaussian filter to the rendered DRR.
- There's also a module in DiffDRR for rendering the 3D scene (CT, X-ray, camera). Perhaps this could help you discover which poses are more likely to produce blocky artifacts? https://vivekg.dev/DiffDRR/api/visualization.html#d-visualization-1

**Comment by dimitriSchreib** [comment]
![4152b618-af88-4eb7-a9d2-e1d64b15c862](https://github.com/eigenvivek/DiffDRR/assets/102990188/81ddd8ac-e855-467e-a489-d98e275efc11)

Interestingly, up-sampling still has significant artifacts. I ran this in multiple batches because my GPU only has 12GB of RAM.

Could the calculation of the ray arc length per voxel be causing this?

**Comment by eigenvivek** [comment]
That's so surprising. Could you please try an even higher resolution, like 1500x1500? (BTW, are you using the `patch_size` argument in the `DRR` initialization? That makes the computation of these high-res DRRs less painless.)

My understanding of these artifacts is that they happen when the rays corresponding to adjacent pixels have a lot of gaps between the voxels they intersect. A real X-ray wouldn't suffer from this issue because one pixel is determined by many (millions?) of X-rays.

**Comment by dimitriSchreib** [comment]
![7b6c1c11-474f-4bb8-a40d-7c89fb4a4bc0](https://github.com/eigenvivek/DiffDRR/assets/102990188/579c5208-e72f-4c46-8bd0-45e079e34d3d)

Here's that image. patch_size is great.

This is from the metamorphosis demo compared to DeepDRR:

![image](https://github.com/eigenvivek/DiffDRR/assets/102990188/936eccad-2c73-4ab5-9bc5-eeb49821f932)

Its interesting that the banding mainly appears horizontally.

**Comment by eigenvivek** [comment]
Well I'm stumped. What's the CT spacing?

**Comment by shenao1994** [comment]
It seemed that voxel spacing was wrong. When you read the CT volume, you can try the following operation: 
`    ct_img = sitk.ReadImage(ctDir)
     spacing1 = ct_img1.GetSpacing()
     spacing[1] = spacing[2]
     spacing[2] = spacing[0]`

**Comment by eigenvivek** [comment]
Hi @dimitriSchreib, does changing the ordering of the spacing as @shenao1994 suggested fix your issue?

If not, I think it's an issue with how DiffDRR formulates ray tracing. I'm not exactly sure how DeepDRR does ray tracing, but "monte carlo" makes me think they're simulating more than one ray per pixel. Something à la [mip-NeRF](https://github.com/google/mipnerf) may overcome the aliasing seen in your example, but I'm sure.

**Comment by eigenvivek** [comment]
Hi @dimitriSchreib, if you have time, could you please install the latest version and try the `trilinear` interpolation backend? It should hopefully fix the majority of your aliasing issue!

It'll be something like
```python
drr = DRR(..., renderer="trilinear")
drr(..., n_points=250)
```

**Comment by eigenvivek** [comment]
Closing with #186. Feel free to reopen if issues persist!
