### ISSUE TITLE
GNCC Issue

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#171]
When using NCC loss, the 2d/3d registration task can converge. But when using GNCC, it cannot converge. Do I need to adjust the parameters of the optimizer?

**Comment by eigenvivek** [comment]
Hi @shenao1994 , I've also often had trouble getting Gradient NCC to converge. I implemented because I saw it in this paper (see Section 2.1) : https://arxiv.org/pdf/1909.10443.pdf

It seems like the authors use a gradient-free optimization scheme to optimize Gradient NCC. Perhaps that works better than gradient-based optimizers for this metric.

If you run the loss landscape visualization example with Gradient NCC, you'll probably find that the landscape isn't as smooth as NCC : https://vivekg.dev/DiffDRR/tutorials/metrics.html

**Comment by eigenvivek** [comment]
Hi @shenao1994 , I've started using something I'm calling multiscale NCC. It's just an average of patch-wise NCC and NCC on the whole image. In practice, it's working a lot better.

This loss landscape is sharp and smooth, which has been leading to really good convergence (this is from some work we just published : https://arxiv.org/pdf/2312.06358.pdf)

<img width="485" alt="Screen Shot 2023-12-12 at 15 39 50" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/558916e1-458e-4e19-8cdc-7f2a17703efb">

Compared to gradient NCC, multiscale NCC has a much smoother landscape. This might explain why optimization with gradient NCC isn't converging.

<img width="467" alt="Screen Shot 2023-12-12 at 15 41 09" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/3e17c13d-bd40-4379-89f5-ac52881e916e">
