### ISSUE TITLE
Questions about accuracy

### ISSUE THREAD

**Issue by khh656** [eigenvivek/DiffDRR#201]
Hello, I now want to generate a 1536*1536 DRR image, but it is too big and will cause insufficient memory. In addition to using the blocking method, I see that your code divides the size by subsample and multiplies the resolution. I also tried subsample and found that the effect is quite good. However, I am worried that multiplying the resolution by subsample will affect the accuracy of subsequent registration? I would be happy if you could answer!

**Comment by eigenvivek** [comment]
Hi @khh656 , you have to multiply the resolution by the subsampling factor. Otherwise, your new detector plane will be smaller than the original.

For example, imagine your original detector plane is 100 x 100 pixels with isotropic 1 mm / pixel spacings (i.e., the resolution). 

You can subsample this detector plane and instead render a 20 x 20 pixel DRR. However, if you don't also scale the resolution by the subsampling factor (i.e., maintain 1 mm / pixel spacing), this 20 x 20 image will be within the original image. In this case, it would simply be a 20 x 20 center crop of the original 100 x 100 DRR.

If instead you multiply the resolution by the subsampling factor (e.g., render a 20 x 20 pixel DRR with 5 mm / pixel spacings), the subsampled detector plane will be the same size as the original. Therefore, you will get a downsampled version of the DRR. 

The only tradeoff here is that the more you downsample the DRR dimensions, the more aliased it will become. Going from 1536 x 1536 -> 256 x 256 doesn't produce very noticeable aliasing artifacts, but if you go smaller than that, the artifacts will become very apparent.

**Comment by khh656** [comment]
Yes, if I go from 1536 x 1536 -> 256 x 256, it is equivalent to multiplying the resolution by 6. Will the subsequent fine registration affect the registration accuracy compared to the original resolution?

**Comment by eigenvivek** [comment]
That's a good question! Not something I've tried before. I would hypothesize that the lower your resolution, the worse the registration accuracy. Higher resolutions would give you more detail, at the tradeoff of slower registration. This is related to the idea of coarse-to-fine registration. This is something that would be very interesting to measure quantitatively.
