### ISSUE TITLE
Problem with the last slice of the image array

### ISSUE THREAD

**Issue by MarkoLeskovar** [eigenvivek/DiffDRR#204]
Hi @eigenvivek,

there seems to be a problem with DRR volume rendering. When I render a volume, the last slice in z-axis is escaping to the wrong position. Take a look at the attached examples. This is the most visible in the knee DRR, where you can see the bottom slice on the top position. Same thing happens with the default chest CT examples, where a artificial halo ring is visible on the top. Could check if there are some indexing errors in the DRR projection code?

![example_02](https://github.com/eigenvivek/DiffDRR/assets/58042850/d38018d2-e4ee-4a87-ab27-9528a7ae77aa)
![example_03](https://github.com/eigenvivek/DiffDRR/assets/58042850/921df137-5106-4ad6-8fa1-a049c44209a4)
![example_01](https://github.com/eigenvivek/DiffDRR/assets/58042850/67d28031-de69-4e2f-8ad8-b262b287549e)

Thank you and best regards,
Marko Leskovar

**Comment by eigenvivek** [comment]
Hi @MarkoLeskovar, thanks for raising this issue. 

I am able to reproduce the issue. I was playing around with some CTs that had segmentation masks and noticed pixels for the femurs floating in weird areas of the DRR.
![siddon](https://github.com/eigenvivek/DiffDRR/assets/29757116/24711cc3-b481-4b7b-9a53-dd30df48b4ba)

In log-scale, this halo artifact you're describing is much more apparent.
![siddon_log](https://github.com/eigenvivek/DiffDRR/assets/29757116/26008c48-2fed-451f-99f4-43a7f531864b)

Interestingly, this doesn't happen if you use `renderer="trilinear"`.
![trilinear_log](https://github.com/eigenvivek/DiffDRR/assets/29757116/41bb4ec3-9579-4014-b22e-5ffd7480ced0)

I'll dig into this and try to find why the bottom z-slice is being projected to the top of the volume render.

**Comment by eigenvivek** [comment]
Tracked the issue to here
https://github.com/eigenvivek/DiffDRR/blob/0e11ee243802c21892b00232223848342e6bc993/diffdrr/renderers.py#L101

`torch.trunc` is the wrong to function to use, since it rounds to the nearest integer towards zero. I need to disambiguate the convention used by affine matrices in DiffDRR and switch to either `torch.round`, `torch.floor`, or `torch.ceil` as appropriate.

**Comment by eigenvivek** [comment]
Also, the `+1` here needs to be removed:

https://github.com/eigenvivek/DiffDRR/blob/0e11ee243802c21892b00232223848342e6bc993/diffdrr/renderers.py#L104-L108

After this correction, preliminary testing shows that only `torch.floor` gets rid of the the halo artifact.

Need to confirm that this makes sense with the volume's affine matrix, but visually the issue is fixed!
