### ISSUE TITLE
Usage of the rotation and translation vectors in the Registration call and the DRR class

### ISSUE THREAD

**Issue by charlesalec** [eigenvivek/DiffDRR#234]
I am trying to render the DRR and initialize the Registration module with translation and rotation parameters that I extract via the convert() function. When I plug them into the DRR class, they work as expected. However, with the Registration module it doesn't render anything at all. I have the following code:

```

rot, trans, random_pose = get_random_offset()
new_pose = pose.compose(random_pose)
new_pose = RigidTransform(new_pose.matrix).to(device)
print('New pose = ', new_pose.matrix)
ground_truth = drr(
    new_pose
)

# For debugging.
plot_drr(ground_truth, cmap='gray')
plt.title('Ground truth (perturbed pose)')

gt_rot, gt_trans = new_pose.convert(parameterization="euler_angles", convention="ZXY")

with torch.no_grad():
    est = drr(
        gt_rot,
        gt_trans,
        parameterization="euler_angles",
        convention="ZXY",
    )

plot_drr(est)
plt.title('Reconstructed from matrix')

# gt_rot = torch.tensor([0, 0, 0], device=device, dtype=torch.float32).unsqueeze(0)
# gt_trans = torch.tensor([-677, -151, 253], device=device, dtype=torch.float32).unsqueeze(0)
reg = Registration(
    drr,
    gt_rot,
    gt_trans,
    parameterization="euler_angles",
    convention="ZXY", 
)
```

Checking the DRR by plotting it with the 'ground_truth' DRR works perfectly when using gt_rot and gt_trans, this doesn't work with the Registration class when I visualize the animation, it doesn't appear at all when I render the first frame (or even directly plotting it before any parameter updates). As far as I understand (I could be wrong though...) these two should work analogously. 

Am I correctly understanding the usage, or is there a different way to use registration pose parameters?

Thank you for all your great work!

**Comment by eigenvivek** [comment]
Hi @charlesalec, thanks for bringing this to my attention. This is due to an issue with `diffdrr.pose.RigidTransform.convert`.

`diffdrr.drr.DRR` and `diffdrr.registration.Registration` assume that, given a rotation `R` and a translation `t`, the camera pose is `pose = t.compose(R)`. Written as a matrix, this looks like `[R | Rt]`. If you look at a CV textbook like Hartley and Zisserman, they explain that this represents a camera center `Rt` and a camera orientation `R`.

In contrast, `diffdrr.pose.RigidTransform.convert` assumes that the camera pose is `pose = [R | t]`. Therefore, when it converts a pose into its underlying parameters, it turns your `R` into Euler angles and returns your `t` without modification.

`[R | t]` is the old convention in DiffDRR and I am pretty sure I will make `[R | Rt]` the new convention going forward (since it directly models how C-arms behave). Thanks for catching this piece of legacy code - will add it to the list of fixes for v0.4.0.

For now, here's a hack that should get you what you need:
```python
# pose : diffdrr.pose.RigidTransform that we want to convert into `R` and `t`
rot, rotxyz = pose.convert("euler_angles", "ZXY")
R = convert(rot, torch.zeros_like(rot), parameterization="euler_angles", convention="ZXY")
xyz = R.inverse()(rotxyz.unsqueeze(0))[0]

reg = Registration(
    drr,
    rot,
    xyz,
    parameterization="euler_angles",
    convention="ZXY", 
)

```

**Comment by charlesalec** [comment]
Aha yes, I see it now. You're right, that did indeed fix it. Thanks for the explanation, that wasn't obvious to me at all that they behaved differently. 

Much appreciated!

**Comment by eigenvivek** [comment]
No problem! I'll keep this open until a fix is merged.
