### ISSUE TITLE
Advice on higher dimensional representations for optimization

### ISSUE THREAD

**Issue by charlesalec** [eigenvivek/DiffDRR#254]
Great work on v0.4 :) it's running great for me so far!

I wanted to ask if you had any advice on using higher dimensional representations for optimization in DiffDRR. [Here](https://vivekg.dev/DiffDRR/tutorials/geometry.html) you mention that Euler angles are the most human-readable, but not the best for optimization. Do you have any advice or experience on which particular representation works best, and on how I can go about using this parameterization in registration with DiffDRR?

Thanks!

**Comment by eigenvivek** [comment]
In the diffpose paper, I compared these representations.

Optimizing se(3) representations of poses worked the best. After diffpose was published, I added a `rotation_9d` parameterization (which implements the SVDO+ paper, see #232). Haven't tested that one yet, so it may be better than se(3).

One other caveat is that in diffpose, rotations and translations were independent. In `v0.4`, rotations and translations are now coupled bc this better simulates how C-arms are parameterized. se(3) internally implements this coupling, one of the reasons I hypothesized it performs better than other parameterizations. Perhaps now that rotations and translations are coupled by default, other parameterizations of camera poses will be competitive with se(3).

If you have an initial pose estimate stored as a `RigidTransform`, you can convert it to any of the other parameterizations listed [here](https://vivekg.dev/DiffDRR/api/drr.html#drr). Then, set up your `Registration` module to optimize parameters in this representation instead of Euler angles. diffpose should have example code implementing this (albeit with a slightly outdated API).

<img width="348" alt="image" src="https://github.com/eigenvivek/DiffDRR/assets/29757116/632252da-c86f-42a2-9a6c-dfd754f68069">

**Comment by charlesalec** [comment]
Understood, thank you! I am currently investigating the capture ranges of DiffDRR on my specific dataset, and was looking for some kind of base-case parameters/options. I am working on v0.4, I'll leave it as Euler angles for now. Thank you!
