### ISSUE TITLE
Aliasing problem when using siddon renderer

### ISSUE THREAD

**Issue by xiechun-tsukuba** [eigenvivek/DiffDRR#265]
Hi @eigenvivek 

Thanks for your great work.
I am trying to render 1536*1536 x-ray images using the code below

```
subject = load_example_ct(orientation="PA")

# Initialize the DRR module for generating synthetic X-rays
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")
drr = DRR(
    subject,     # An object storing the CT volume, origin, and voxel spacing
    sdd=1020.0,  # Source-to-detector distance (i.e., focal length)
    height=1536,  # Image height (if width is not provided, the generated DRR is square)
    delx=0.194,    # Pixel spacing (in mm)
    patch_size=512,  # Patch size for rendering (in pixels)
).to(device)

# Set the camera pose with rotations (yaw, pitch, roll) and translations (x, y, z)
rotations = torch.tensor([[0.0, 0.0, 0.0]], device=device)
translations = torch.tensor([[0.0, -1000.0, 0.0]], device=device)

img = drr(rotations, translations, parameterization="euler_angles", convention="ZXY")

# save img as png file
plt.imsave('drr.png', img.squeeze().cpu().detach(), cmap='gray')

```

However, the rendered image has pronounced horizontal aliasing artifacts as shown below. 
![drr1](https://github.com/eigenvivek/DiffDRR/assets/83652157/7216a2d1-19e1-418c-ae55-93b20f4997d3)

I didn't observe such aliasing when using `trilinear` renderer or DeepDRR.  Could you please help me figure out the reason and how to fix it? Thanks.

**Comment by eigenvivek** [comment]
Hi @xiechun-tsukuba, the reason for this is simply that Siddon's method is more susceptible to aliasing than trilinear interpolation.

In trilinear interpolation (which is also what DeepDRR uses in its backend), neighboring voxels are averaged even if the ray drawn from the source point to the target point at the center of a pixel does not intersect those voxels.

In Siddon's method, only the voxels that a ray intersects contribute to the rendered intensity. This is different from how real X-rays work because in real X-ray images, each pixel is the composition of millions of rays (i.e., X-rays would be more accurately represented by "cone-casting" instead of ray-casting).

However, Siddon's method produces more accurate X-rays than trilinear interpolation at *lower resolutions*. So that's a tradeoff that you have to optimize for. In practice, I've found that Siddon's method works better for 2D/3D registration, but this is a dataset-specific finding. I bet there are situations in which one method might be better than another.

**Comment by eigenvivek** [comment]
See also #172 and #186 

Closing for now, feel free to reopen if you have further questions.
