### ISSUE TITLE
About Reconstruction 

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#289]
Hello, I am studying the method of 3D Gaussian splatting rendering DRR recently. I reproduced the code about reconstruction in your tutorial. The optimized results are delighted. 
![微信图片_20240627152749](https://github.com/eigenvivek/DiffDRR/assets/28835780/95f2161a-dfa1-4a18-89c1-8bb411688ce3)
But I found that after optimization, the **Reconstruction** class still needs to input parameters such as volume and pose, and then render with Siddon method to generate DRR. What is the difference between this and **diffdrr** explicit rendering? This is what bothers me.

**Comment by eigenvivek** [comment]
Following [this section of the reconstruction tutorial](https://vivekg.dev/DiffDRR/tutorials/reconstruction.html#initialize-a-moving-drr-from-a-random-volume), the `Reconstruction` class needs to be initialized with a `density` and `pose`. The `density` in this example is initialized as all zeros, and throughout the coarse of the optimization, it gets iteratively refined. The ground truth `pose` is needed because it specifies the viewpoint for the renderer. This is equivalent to any other reconstruction approach (e.g., Gaussian splatting, NeRF, etc) where the ground truth camera pose for each image is either estimated or known _a priori_. The difference between this and explicit rendering is that the `volume` is the unknown variable for which we are solving.

**Comment by shenao1994** [comment]
Yeah, I got it! Thank you for your patient explanation! I also found that the density model obtained by this optimization method is not robust enough. I save the converged parameters as a **pth** file. When inputting a new perspective for prediction, the generated DRR effect is relatively poor when the translation or rotation is too large. Can we replace the parameterized density with 3D GS (using reconstruction tutorial). Train using a large amount of synthetic data to obtain a robust 3D GS model. This is my current idea! Actually, there is already a lot of work on 3D GS, but there are still very few methods that combine it with DRR generation. This is an article about generating DRR images using 3D GS. （ https://arxiv.org/abs/2403.04116 ）

**Comment by eigenvivek** [comment]
Cool! Yeah it's an entirely separate research project to implement 3DGS w/ DiffDRR. I've read the paper you linked, and here are two others that do a similar thing

- https://arxiv.org/abs/2404.03126
- https://arxiv.org/abs/2406.02518

If you implement 3DGS w/ DiffDRR, I'd be very happy to work with you on getting a PR into the package. Feel free to open a new issue if you go down this route!
