### ISSUE TITLE
Backproject issue

### ISSUE THREAD

**Issue by shenao1994** [eigenvivek/DiffDRR#325]
I am conducting an experiment on 2D back projection to 3D using **Diffdrr** (0.4.3). It is correct to use the function **perspective_projection** to project 3D onto 2D. But when I use the **inverse_projection** function, I cannot restore the 3D points. I checked the code and found that the projection is divided by **z**. When backprojecting, **SDD** is used. Is it impossible to accurately obtain **z** when using single view back projection? Therefore, it is impossible to restore to the original 3D points.
**_perspective_projection:_**
`z = x[..., -1].unsqueeze(-1).clone()`
`x = x / z`
**_inverse_projection:_**
`x = self.detector.sdd * torch.einsum(
        "ij, bnj -> bni",
        self.detector.intrinsic.inverse(),
        pad(pts, (0, 1), value=1), )`
**Origin 3d points**
![image](https://github.com/user-attachments/assets/99efcdf9-2c40-496e-a9d5-8f0fb49e76df)
**Backprojected 3d points**
![image](https://github.com/user-attachments/assets/2cd46f60-68d3-44ab-a1cc-46ff03fb9956)

**Comment by eigenvivek** [comment]
Hi @shenao1994 small misunderstanding here:
- `perspective_projection` maps 3D points to a 2D points
- `inverse_projection` maps 2D points to 3D points *embedded on a 2D plane in 3D*

When backprojecting 2D points, we don't know what depth those points originated from. All we know is that they lie somewhere on the ray from the source to target point. The `inverse_projection` function maps them to detector plane in 3D, which is why they're multiplied by `SDD`.

**Comment by shenao1994** [comment]
> Hi @shenao1994 small misunderstanding here:
> 
> * `perspective_projection` maps 3D points to a 2D points
> * `inverse_projection` maps 2D points to 3D points _embedded on a 2D plane in 3D_
> 
> When backprojecting 2D points, we don't know what depth those points originated from. All we know is that they lie somewhere on the ray from the source to target point. The `inverse_projection` function maps them to detector plane in 3D, which is why they're multiplied by `SDD`.

I got it. I've misunderstood about inverse projection.
