### ISSUE TITLE
Hello World reports an error while running

### ISSUE THREAD

**Issue by asjeff** [eigenvivek/DiffDRR#345]
Hi,
I used pip install diffdrr and wanted to run the Hello world code, but it reported an error in line 26: 
()
      didn't match because some of the keywords were incorrect: dim
 * (int dim, bool keepdim)
 * (name dim, bool keepdim)
 please help me solve this problem, thanks!

**Comment by eigenvivek** [comment]
usually that’s a torch version issue

can you make sure you’re on the latest version of torch?
On Nov 19, 2024 at 07:15 -0500, asjeff ***@***.***>, wrote:

Hi,
I used pip install diffdrr and wanted to run the Hello world code, but it reported an error in line 26:
()
didn't match because some of the keywords were incorrect: dim

  *   (int dim, bool keepdim)
  *   (name dim, bool keepdim)
please help me solve this problem, thanks!

**Comment by asjeff** [comment]
thanks！I will check it

**Comment by asjeff** [comment]
hi,
I'm using pytorch 2.1.2, i want to know only 2.5.1 can use the diffdrr 0.4.4？

**Comment by eigenvivek** [comment]
not sure about all the version compatabilities, but i’m pretty sure pytorch 2.2+ works
On Nov 19, 2024 at 09:20 -0500, asjeff ***@***.***>, wrote:

hi,
I'm using pytorch 2.1.2, i want to know only 2.5.1 can use the diffdrr 0.4.4？

**Comment by eigenvivek** [comment]
closing for now, feel free to reopen if you're still facing issues
